### ISSUE TITLE
ms-swift 3.0 donot support `get_default_template_type`

### ISSUE THREAD

**Issue by momaek** [modelscope/evalscope#378]
Please check https://github.com/modelscope/ms-swift/blob/b2d3ef503ece8642b6ca7ab3862b59e9f2846d47/docs/source_en/Instruction/Frequently-asked-questions.md#q78-does-swift30-not-support-get_default_template_type

**Comment by Yunnglin** [comment]
Is there any promblem? Could you please describe it in detail?

**Comment by momaek** [comment]
- ms_swift:  3.2.0.post2
- evalscope: 0.12.0

toolbench.yaml
```
infer_args:
  model_name_or_path: /models/Qwen/QwQ-32B      # absolute path is recommended
  model_type: qwq
  data_path: /data/toolbench_static   # absolute path is recommended
  deploy_type: swift
  max_new_tokens: 4096
  num_infer_samples: null
  output_dir: output_res
eval_args:
  input_path: output_res
  output_path: output_res
```

Got error: 
from swift.llm import (
ImportError: cannot import name 'get_default_template_type' from 'swift.llm' 

downgrade `ms_swift` to  2.x. It works fine. But `ms-swift` 2.x Donot support QwQ-32B.
